// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_jdNNdDmp9T4O4xxUvDMb5qYdIid-0M',
    appId: '1:649961935509:web:91d6e2b01211913010819c',
    messagingSenderId: '649961935509',
    projectId: 'scholar-chat-app-f405a',
    authDomain: 'scholar-chat-app-f405a.firebaseapp.com',
    storageBucket: 'scholar-chat-app-f405a.firebasestorage.app',
    measurementId: 'G-QSNLBNS6JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHaUBTa4gH0B8A1KsROzq8nCMd1XmVQ8',
    appId: '1:649961935509:android:92c8064349f7850410819c',
    messagingSenderId: '649961935509',
    projectId: 'scholar-chat-app-f405a',
    storageBucket: 'scholar-chat-app-f405a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjopZxPHe8CfjDRq0TgnE0zYXEpQdc_Pw',
    appId: '1:649961935509:ios:42b5c2b33aba779810819c',
    messagingSenderId: '649961935509',
    projectId: 'scholar-chat-app-f405a',
    storageBucket: 'scholar-chat-app-f405a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjopZxPHe8CfjDRq0TgnE0zYXEpQdc_Pw',
    appId: '1:649961935509:ios:42b5c2b33aba779810819c',
    messagingSenderId: '649961935509',
    projectId: 'scholar-chat-app-f405a',
    storageBucket: 'scholar-chat-app-f405a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC_jdNNdDmp9T4O4xxUvDMb5qYdIid-0M',
    appId: '1:649961935509:web:ce2d36f4de319a8f10819c',
    messagingSenderId: '649961935509',
    projectId: 'scholar-chat-app-f405a',
    authDomain: 'scholar-chat-app-f405a.firebaseapp.com',
    storageBucket: 'scholar-chat-app-f405a.firebasestorage.app',
    measurementId: 'G-4RXJXJRSTD',
  );
}
